### ISSUE TITLE
Final Capstone project - Team members

### ISSUE THREAD

**Issue by Hamzaoutdoors** [Hamzaoutdoors/rentalcars_backend#21]
## This is the repository for our final capstone at `Microverse` 😄, we are four team members working on this project : 

Say welcome to ⏬ : 

 -  @Laylo309 (a.k.a the sleepy Oracle) - Member A
 - @nelsinofrancisco (A.k.a the Big Oracle)  - Member B
 - @JbirdL86 (a.k.a The Bird) - Member C
 - @Hamzaoutdoors (a.k.a El Patron) - Member D

# the link for our project: [Link here](https://github.com/Hamzaoutdoors/motorcycles_finalcapstone/projects/1)

**Comment by MuriloRoque** [comment]
Hi @Hamzaoutdoors, @JbirdL86, @Laylo309, @nelsinofrancisco,

In my opinion, your project is complete! There is nothing else to say other than... it's time to start it :shipit:

Good luck! 🎉

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.
